apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-operator
  namespace: default
  labels:
    app: email-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-operator
  template:
    metadata:
      labels:
        app: email-operator
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      serviceAccountName: email-operator
      containers:
      - name: operator
        image: email-operator:dotnet
        imagePullPolicy: Never
