apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emailsenderconfigs.mailerlite.com
spec:
  group: mailerlite.com
  names:
    kind: EmailSenderConfig
    listKind: EmailSenderConfigList
    plural: emailsenderconfigs
    singular: emailsenderconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: Specification of the kubernetes object.
            properties:
              apiTokenSecretRef:
                type: string
              senderEmail:
                type: string
            type: object
        type: object
    served: true
    storage: true